Repository QuizFight/QuizFight, pull requests merged in 2019-03, with the labels that each got.

#44 Adjust message question specification
  app/src/main/java/org/quizfight/quizfight/Client.kt
  app/src/main/java/org/quizfight/quizfight/QuizActivity.kt
  common/src/main/kotlin/org/quizfight/common/messages/Message.kt
  common/src/main/kotlin/org/quizfight/common/question/FourAnswersQuestion.kt
  common/src/main/kotlin/org/quizfight/common/question/Question.kt
  common/src/main/kotlin/org/quizfight/common/question/RangeQuestion.kt
  server/src/main/kotlin/org/quizfight/parser/XmlParser.kt
  server/src/main/kotlin/org/quizfight/questionStore/QuestionSelector.kt
  server/src/main/kotlin/org/quizfight/questionStore/QuestionStore.kt
  server/src/main/kotlin/org/quizfight/server/Game.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/Launcher.kt
  server/src/main/kotlin/org/quizfight/server/Player.kt
  server/src/main/resources/xml/choiceQuestions.xml
  server/src/main/resources/xml/guessQuestions.xml
Labels: area/backend, area/communication, area/frontend, type/enhancement, type/task

#53 nickname for gameCreation
  common/src/main/kotlin/org/quizfight/common/messages/Message.kt
Labels: area/backend, area/communication, area/frontend, type/fix

#54 Add functionalities for MasterServer
  server/src/main/kotlin/org/quizfight/server/MasterServer.kt
Labels: area/backend, type/enhancement, type/requirement, type/task

#56 Feature/launcher
  server/src/main/kotlin/org/quizfight/server/Dialog.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/Launcher.kt
Labels: area/backend, type/enhancement

#59 Feature/master and game server connection
  server/src/main/kotlin/org/quizfight/server/Dialog.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/MasterServer.kt
Labels: area/backend, area/communication, type/task

#60 Feature/game creation
  app/src/main/java/org/quizfight/quizfight/CreateGameActivity.kt
  common/src/main/kotlin/org/quizfight/common/Connection.kt
  server/src/main/kotlin/org/quizfight/server/Dialog.kt
  server/src/main/kotlin/org/quizfight/server/Game.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/Launcher.kt
  server/src/main/kotlin/org/quizfight/server/MasterServer.kt
  server/src/main/kotlin/org/quizfight/server/ServerUtils.kt
Labels: area/backend, area/communication, type/enhancement

#61 Feature/game server updates
  app/src/main/java/org/quizfight/quizfight/CreateGameActivity.kt
  common/src/main/kotlin/org/quizfight/common/messages/Message.kt
  server/src/main/kotlin/org/quizfight/server/Dialog.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/MasterServer.kt
Labels: area/backend, type/enhancement

#65 Client gets games from GameServers
  common/src/main/kotlin/org/quizfight/common/messages/Message.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/MasterServer.kt
  server/src/main/kotlin/org/quizfight/server/ServerUtils.kt
Labels: area/backend, area/communication, type/enhancement

#66 Serverside join game procedure
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
Labels: area/backend, type/enhancement

#67 Game starts if max players is reached
  server/src/main/kotlin/org/quizfight/server/Game.kt
Labels: area/backend, type/task

#71 Fix "Unresolved reference R" message
  build.gradle
Labels: area/frontend, type/fix

#74 MsgPlayerCount, Players with id as String, ServerUtilsFunction return…
  common/src/main/kotlin/org/quizfight/common/messages/Message.kt
  server/src/main/kotlin/org/quizfight/server/Game.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/MasterServer.kt
  server/src/main/kotlin/org/quizfight/server/Player.kt
  server/src/main/kotlin/org/quizfight/server/ServerUtils.kt
Labels: area/backend, type/task

#91 Added test for withHandlers
  common/src/test/kotlin/org/quizfight/common/ConnectionTest.kt
Labels: area/communication

#101 Fix reconnecting to master after ending a game
  app/src/main/java/org/quizfight/quizfight/Client.kt
  app/src/main/java/org/quizfight/quizfight/QuizActivity.kt
  app/src/main/java/org/quizfight/quizfight/StartActivity.kt
Labels: area/communication, area/frontend, type/fix

#104 Add app icon
  app/src/main/ic_launcher-web.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: area/frontend, type/enhancement
