Repository QuizFight/QuizFight, pull requests merged in 2019-01, with the labels that each got.

#5 Remove .idea directory, adjust .gitignore
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: type/fix

#6 Fix common dependency
  app/build.gradle
  server/build.gradle
Labels: type/fix

#7 Add connection class
  common/build.gradle
  common/src/main/kotlin/org/quizfight/common/Connection.kt
Labels: area/communication, type/enhancement, type/task

#9 Basic question handling with XML
  common/src/main/kotlin/org/quizfight/common/question/FourAnswersQuestion.kt
  common/src/main/kotlin/org/quizfight/common/question/Question.kt
  common/src/main/kotlin/org/quizfight/common/question/RangeQuestion.kt
  server/res/xml/fourAnswerQuestions.xml
  server/res/xml/rangedQuestions.xml
  server/src/main/kotlin/org/quizfight/parser/XmlParser.kt
  server/src/main/kotlin/org/quizfight/questionStore/QuestionStore.kt
Labels: area/backend, area/frontend, type/enhancement, type/task

#11 Add coroutine support
  app/build.gradle
  build.gradle
  common/build.gradle
  server/build.gradle
Labels: type/enhancement
