Repository QuizFight/QuizFight, pull requests merged in 2019-02, with the labels that each got.

#15 QuestionSelector
  server/res/xml/fourAnswerQuestions.xml
  server/res/xml/rangedQuestions.xml
  server/src/main/kotlin/org/quizfight/questionStore/QuestionSelector.kt
  server/src/main/kotlin/org/quizfight/questionStore/QuestionStore.kt
Labels: area/backend, type/enhancement, type/task

#19 Feature/fill games with questions
  server/out/production/classes/META-INF/server_main.kotlin_module
  server/out/production/classes/org/quizfight/parser/XmlParser.class
  server/out/production/classes/org/quizfight/questionStore/QuestionStore.class
  server/out/production/classes/org/quizfight/server/ServerKt.class
  server/src/main/kotlin/org/quizfight/server/Game.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/Launcher.kt
Labels: area/backend, type/enhancement, type/task

#20 Connection improvements (internal socket transfer, closing)
  common/src/main/kotlin/org/quizfight/common/Connection.kt
Labels: area/communication, type/enhancement

#23 Implementation agnostic connection usage in server
  server/src/main/kotlin/org/quizfight/server/Game.kt
  server/src/main/kotlin/org/quizfight/server/GameServer.kt
  server/src/main/kotlin/org/quizfight/server/Player.kt
Labels: area/backend, area/communication, type/enhancement, type/task

#24 Connection Unit Test
  common/build.gradle
  common/src/main/kotlin/org/quizfight/common/Connection.kt
  common/src/test/kotlin/org/quizfight/common/ConnectionTest.kt
Labels: area/communication, type/enhancement, type/fix

#25 Testing socket with delay
  common/src/test/kotlin/org/quizfight/common/ConnectionTest.kt
  common/src/test/kotlin/org/quizfight/common/test/DelayedSocket.kt
Labels: area/communication, type/enhancement

#28 Moved resources, added Resource loading, fixed small bug appearing while printing a games questions
  server/src/main/kotlin/org/quizfight/parser/XmlParser.kt
  server/src/main/kotlin/org/quizfight/server/Game.kt
  server/src/main/resources/xml/fourAnswerQuestions.xml
  server/src/main/resources/xml/rangedQuestions.xml
Labels: area/backend, type/bug, type/fix

#36 Fix withHandlers (var handlers instead of val)
  common/src/main/kotlin/org/quizfight/common/Connection.kt
Labels: area/communication, type/fix

#34 Refactor frontend networking
  app/build.gradle
  app/src/main/java/org/quizfight/quizfight/Person.kt
  app/src/main/java/org/quizfight/quizfight/QuizActivity.kt
  app/src/main/java/org/quizfight/quizfight/ServerTest.kt
  server/src/main/kotlin/org/quizfight/server/Tester.kt
Labels: area/frontend, type/enhancement, type/fix

#41 Deleted trash
  server/out/production/classes/META-INF/server_main.kotlin_module
  server/out/production/classes/org/quizfight/parser/XmlParser.class
  server/out/production/classes/org/quizfight/questionStore/QuestionStore.class
  server/out/production/classes/org/quizfight/server/ServerKt.class
Labels: area/backend
